---
- name: secure the warning file
  hosts: servers
  become: true

  tasks:
    - name: change owner and permissions
      ansible.builtin.file:
        path: /etc/motd
        owner: root
        group: root
        mode: '0444'
