---
- name: Create a directory
  hosts: servers
  become: true
  tasks:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: /opt/ansible_lab
        state: directory
        mode: '0777'
